### ISSUE TITLE
Port mismach

### ISSUE THREAD

**Issue by tvainika** [loginakhil/karapace-testing#1]
test.py Karapace URL is 8081 but Karapace container in compose.yml is listening 8080.

**Comment by loginakhil** [comment]
Looks like it's working fine now, thanks for the input @tvainika  🙇

**Comment by loginakhil** [comment]
Hello @tvainika ,

I came across another bug with references.

I have pushed it as a new commit name [bug-2 using references](https://github.com/loginakhil/karapace-testing/commit/6f032244aae515132c95fbaff8c5d0498b8a144c).

Could you please take a look :pray:

**Comment by tvainika** [comment]
Hello @loginakhil,

karapace main branch includes now a fix for the bug you have found. If you find any new bugs, please let us know by opening issues in karapace repository itself. That's easiest way to keep track.
